version: '3'

services:
  nginx:
    build: ${DOCKER_PATH}/nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:${PROJECT_PATH}
      - ${DOCKER_PATH}/nginx/nginx.sh:/var/nginx.sh
      - ${DOCKER_PATH}/nginx/sites-enabled:/var/sites-enabled
      - ${DOCKER_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
    command: ./var/nginx.sh
  php:
    build: ${DOCKER_PATH}/php
    volumes:
      - .:${PROJECT_PATH}
      - ~/.cache/composer:/.cache/composer
    working_dir: ${PROJECT_PATH}
    depends_on:
      - mariadb
      - maildev
      - redis
  redis:
    build: ${DOCKER_PATH}/redis
  mariadb:
    build: ${DOCKER_PATH}/mariadb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - /var/data:/var/lib/mysql
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
  node:
    build: ${DOCKER_PATH}/node
    ports:
      - "${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}"
    volumes:
      - .:${PROJECT_PATH}
      - ~/.cache/npm:/root/.npm
    working_dir: ${PROJECT_PATH}
    command: "npm run dev"
  laravel_echo_server:
    build: ${DOCKER_PATH}/node
    ports:
      - "${LARAVEL_ECHO_SERVER_PORT}:${LARAVEL_ECHO_SERVER_PORT}"
    volumes:
      - .:${PROJECT_PATH}
    working_dir: ${PROJECT_PATH}
    depends_on:
      - redis
      - nginx
    command: "laravel-echo-server start --force"
